blank_issues_enabled: false
contact_links:
  - name: "ALL translator issues and requests: Post to the Zotero Forums"
    url: https://forums.zotero.org/post/discussion
    about: Do not use GitHub Issues to report problems saving pages or to request a new translator. Make a forum post. Zotero developers will create new issues in the relevant repositories.
